name: Docker Build
on:
  push:
    tags:
      - v**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.2
        with:
          strip_v: true # Optional: Remove 'v' character from version
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: developerlee-docker.pkg.coding.net
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build -f Dockerfile -t developerlee-docker.pkg.coding.net/cc0/9527/cat-token-box:${{steps.tag.outputs.tag}} .
      - name: Docker image push
        run: docker push developerlee-docker.pkg.coding.net/cc0/9527/cat-token-box:${{steps.tag.outputs.tag}}
